version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://db:27017/menheal-detector
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "worker"]
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://db:27017/menheal-detector
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
